[package]
name = "backend"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.0"
ic-cdk = "0.12.0"
serde = "1.0.193"
serde_json = "1.0.108"
ic-stable-structures = "0.6.0"
serde_bytes = "0.11"

[build-dependencies]
ic-cdk-bindgen = "0.1.3"
